[package]
name = "comprehensive-rust"
version = "0.1.0"
edition = "2021"

[workspace]

members = [ "elevator_event", "generic_data_types",
    "helloworld", "shared_reference", "trait_bound",
]

[dependencies]
